# Generated by Django 4.2.9 on 2024-06-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_portfolioitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
