# Generated by Django 4.2.9 on 2024-02-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0004_userlocation_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='nickname',
            field=models.CharField(default=models.CharField(max_length=250), max_length=250),
        ),
    ]
