# Generated by Django 4.2.9 on 2024-02-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0006_auto_20240213_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='nickname',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
