# Generated by Django 4.2.9 on 2024-02-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0007_alter_userlocation_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='country_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
