# Generated by Django 4.2.9 on 2024-02-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0003_alter_sudoku_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudoku',
            name='win',
            field=models.BooleanField(default=False),
        ),
    ]
