# Generated by Django 4.2.9 on 2024-02-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0002_alter_sudoku_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudoku',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
