# Generated by Django 4.2.9 on 2024-03-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0005_alter_sudoku_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sudoku',
            name='solution',
        ),
    ]
