# Generated by Django 4.2.9 on 2024-02-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='address',
            field=models.CharField(max_length=250),
        ),
    ]
