# Generated by Django 4.2.9 on 2024-02-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_alter_userlocation_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='lat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='lon',
            field=models.CharField(max_length=100),
        ),
    ]
