# Generated by Django 4.2.9 on 2024-02-13 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0005_alter_userlocation_nickname'),
    ]

    operations = [
    ]
